///////////////////////////////////////////////////////////
//  LoadOtherXmlCommand.as
//  Macromedia ActionScript Implementation of the Class LoadOtherXmlCommand
//  Generated by Enterprise Architect
//  Created on:      08-六月-2011 17:04:02
//  Original author: LuXianli
///////////////////////////////////////////////////////////

package com.raytoon.cannonfodder.puremvc.controller
{
	import com.raytoon.cannonfodder.puremvc.model.XMLProxy;
	import org.puremvc.as3.interfaces.INotification;
	import org.puremvc.as3.patterns.command.SimpleCommand;
	/**
	 * @author LuXianli
	 * @version 1.0
	 * @created 08-六月-2011 17:04:02
	 */
	public class LoadOtherXmlCommand extends SimpleCommand
	{
		private static var xmlArr:Array = [];
		
		public static function setXmlName(xmlName:String):void {
			
			if (xmlName)
				xmlArr[xmlArr.length] = xmlName;
		}
		
		override public function execute(notification:INotification):void 
		{
			xmlArr[xmlArr.length] = "ANN.xml";
			xmlArr[xmlArr.length] = "Event.xml";
			xmlArr[xmlArr.length] = "Equipment.xml";
			xmlArr[xmlArr.length] = "API.xml";
			xmlArr[xmlArr.length] = "DailyGift.xml";
			xmlArr[xmlArr.length] = "FeedInfo.xml";
			xmlArr[xmlArr.length] = "FormList.xml";
			xmlArr[xmlArr.length] = "GameGuide.xml";
			xmlArr[xmlArr.length] = "GemSkills.xml";
			xmlArr[xmlArr.length] = "GiftBag.xml";
			xmlArr[xmlArr.length] = "HeroInfo.xml";
			xmlArr[xmlArr.length] = "HeroNameRace.xml";
			xmlArr[xmlArr.length] = "HeroLevelInfo.xml";
			xmlArr[xmlArr.length] = "HeroSkillsInfo.xml";
			xmlArr[xmlArr.length] = "LevelInfo.xml";
			xmlArr[xmlArr.length] = "MainTaskInfo.xml";
			xmlArr[xmlArr.length] = "MapInfo.xml";
			xmlArr[xmlArr.length] = "Materials.xml";
			xmlArr[xmlArr.length] = "Props.xml";
			xmlArr[xmlArr.length] = "SoldierInfo.xml";
			xmlArr[xmlArr.length] = "SoldierLevelInfo.xml";
			xmlArr[xmlArr.length] = "SoldierSkillsInfo.xml";
			xmlArr[xmlArr.length] = "SoldierTechTree.xml";
			xmlArr[xmlArr.length] = "Sounds.xml";
			xmlArr[xmlArr.length] = "TowerInfo.xml";
			xmlArr[xmlArr.length] = "TowerLevelInfo.xml";
			xmlArr[xmlArr.length] = "TowerSkillsInfo.xml";
			xmlArr[xmlArr.length] = "TowerTechTree.xml";
			xmlArr[xmlArr.length] = "UISite.xml";
			
			var xmlProxy:XMLProxy = facade.retrieveProxy(XMLProxy.NAME) as XMLProxy;
			xmlProxy.requestOtherXml(xmlArr);
		}
	}//end LoadOtherXmlCommand

}