///////////////////////////////////////////////////////////
//  BulletLink.as
//  Macromedia ActionScript Implementation of the Class BulletLink
//  Generated by Enterprise Architect
//  Created on:      13-七月-2011 11:41:22
//  Original author: LuXianli
///////////////////////////////////////////////////////////

package com.raytoon.cannonfodder.puremvc.view.ui.optionMainLayer.element.bullet
{
	import com.raytoon.cannonfodder.puremvc.view.ui.optionMainLayer.element.Element;
	import com.raytoon.cannonfodder.puremvc.view.ui.optionMainLayer.OptionMainLayer;
	import com.raytoon.cannonfodder.puremvc.view.ui.UIMain;
	/**
	 * @author LuXianli
	 * @version 1.0
	 * @created 13-七月-2011 11:41:22
	 */
	public class BulletLink extends Element
	{
		//子弹射击单位
		private var _shooter:Element;
		//链路数组
		private var _linkArr:Array = [];
		public function BulletLink(from:Element, linkArr:Array) {
			super();
			row = 20;
			_shooter = from;
			_linkArr = linkArr;
			attack = from.attack;
			x = from.x;
			y = from.y;
			
		}
		
		/**
		 * 重新渲染单位
		 */
		override public function rendering():void 
		{
			if (_linkArr) {
				//检测链路攻击
				checkHurt();
			}else {
				removeThis();
			}
			
		}
		private var _hurtArr:Array = [];
		/**
		 * 检测链路是否击中单位
		 */
		private function checkHurt():void {
			
			_hurtArr = (UIMain.getInstance(OptionMainLayer.NAME) as OptionMainLayer).attackArr;
			
			for each(var element:Element in _hurtArr) {
				if (element.moveType == 404) continue;
				var _angle:Number = Math.atan2(element.position.y - _shooter.position.y, element.position.x - _shooter.position.x) / Math.PI * 180;
				
				for each(var num:Number in _linkArr) {
					
					if (num - _angle >= -1 && num - _angle <= 1) 
						element.downHp(attack);
				}
			}
			attack = 0;
			removeThis();
		}
		
	}//end BulletLink

}