///////////////////////////////////////////////////////////
//  OrePaper.as
//  Macromedia ActionScript Implementation of the Class OrePaper
//  Generated by Enterprise Architect
//  Created on:      29-九月-2011 17:32:20
//  Original author: LuXianli
///////////////////////////////////////////////////////////

package com.raytoon.cannonfodder.puremvc.view.ui.optionMainLayer.element {
	import com.raytoon.cannonfodder.puremvc.view.ui.buffLayer.BuffLayer;
	import com.raytoon.cannonfodder.puremvc.view.ui.soundLayer.SoundLayer;
	import com.raytoon.cannonfodder.puremvc.view.ui.UIMain;
	import com.raytoon.cannonfodder.puremvc.view.ui.optionMainLayer.OptionMainLayer;
	import com.raytoon.cannonfodder.tools.BaseSprite;
	import com.raytoon.cannonfodder.tools.utils.NumberFont;
	import com.raytoon.cannonfodder.tools.utils.UICommand;
	import flash.events.Event;
	import flash.text.TextField;

	import flash.display.MovieClip;
	import flash.display.SimpleButton;
	import flash.display.Sprite;
	import flash.events.MouseEvent;
	import flash.events.TimerEvent;
	import flash.geom.Point;
	import flash.system.ApplicationDomain;
	import flash.utils.Timer;
	/**
	 * @author LuXianli
	 * @version 1.0
	 * @created 29-九月-2011 17:32:20
	 */
	public class OrePaper extends BaseSprite
	{
		public var _glodBtnTimer:Timer;
		private var _glodBtnArr:Array = new Array();
		private var glodBtn:SimpleButton;
		private var glodClass:Class;
		private var _plusPaperSum:int = 1; //增加手纸数
		private var _oneLayer:Sprite;
		private var _twoLayer:Sprite;
		private var _paperSite:int = 2;
		private var _cutPaperTime:int = 1;
		private var creatMC:MovieClip;
		private var _paperFlag:Boolean = true;
		public function OrePaper(plusPaperSum:int,cutPaperTime:int,paperSite:int = 2,showBtnFlag:Boolean = true){
			super(true,true);
			_plusPaperSum = plusPaperSum;
			_paperSite = paperSite;
			_cutPaperTime = cutPaperTime;
			_oneLayer = new Sprite();
			addChild(_oneLayer);
			_twoLayer = new Sprite();
			addChild(_twoLayer);
			
			if ((UIMain.getInstance(BuffLayer.NAME) as BuffLayer).checkBuffView("p") > 0 && UICommand.t.stateSecond == "")_paperFlag = false;
			
			if (showBtnFlag) {
				
				var creatClass:Class = ApplicationDomain.currentDomain.getDefinition("OreCreateMovie") as Class;
				creatMC = new creatClass() as MovieClip;
				creatMC.addFrameScript(3, showOrePaper);
				creatMC.addEventListener("oreCreateMoviePlayComplete", removeOreCreateMovie);
				_twoLayer.addChild(creatMC);
				creatClass = null;
			}
			else {
				shadeMovie();
			}
		}
		
		private function removeOreCreateMovie(event:Event):void {
			
			if (creatMC) {
				creatMC.removeEventListener("oreCreateMoviePlayComplete", removeOreCreateMovie);
				_twoLayer.removeChild(creatMC);
				creatMC = null;
				
				if (!_paperFlag) {
					
					removeGlodBtn();
					(UIMain.getInstance(OptionMainLayer.NAME) as OptionMainLayer).playPaperSoldierMovie();
				}
			}
		}
		
		private function showOrePaper():void {
			
			glodClass = ApplicationDomain.currentDomain.getDefinition("OreBtnPaper"+String(_paperSite)) as Class;
			glodBtn = new glodClass() as SimpleButton;
			_oneLayer.addChild(glodBtn);
			if(_paperFlag)glodBtn.addEventListener(MouseEvent.ROLL_OVER, removeGlodBtn);
			
			_glodBtnTimer = new Timer(1000);
			_glodBtnTimer.addEventListener(TimerEvent.TIMER, removeTimerGlod);
			_glodBtnTimer.start();
		}
		
		private function removeTimerGlod(event:TimerEvent):void {
			
			if (_glodBtnTimer.currentCount == _cutPaperTime) {
				
				_glodBtnTimer.reset();
				_glodBtnTimer.removeEventListener(TimerEvent.TIMER, removeTimerGlod);
				_glodBtnTimer = null;
				glodBtn.removeEventListener(MouseEvent.ROLL_OVER, removeGlodBtn);
				(UIMain.getInstance(OptionMainLayer.NAME) as OptionMainLayer).removeOrePaper(this);
			}
			else if (_glodBtnTimer.currentCount == _cutPaperTime - 2){
				this.alpha = 0.5;
			}
			
		}
		
		private function removeGlodBtn(event:MouseEvent = null):void {
			
			killTimer();
			if(glodBtn && _paperFlag)glodBtn.removeEventListener(MouseEvent.ROLL_OVER, removeGlodBtn);
			(UIMain.getInstance(SoundLayer.NAME) as SoundLayer).playSound("GetPaperSound");
			shadeMovie();
		}
		
		public function killTimer():void {
			
			if (_glodBtnTimer) {
				_glodBtnTimer.reset();
				_glodBtnTimer.removeEventListener(TimerEvent.TIMER, removeTimerGlod);
				_glodBtnTimer = null;
			}
		}
		private var _endPoint:Point = new Point(25,512);
		private var _moveX:Number;
		private var _moveY:Number;
		private var _shadeMovieTimer:Timer;
		private function shadeMovie():void {
			
			if ((UIMain.getInstance(OptionMainLayer.NAME) as OptionMainLayer).paperPoint)
				_endPoint = (UIMain.getInstance(OptionMainLayer.NAME) as OptionMainLayer).paperPoint;
			
			_moveX = ( _endPoint.x - this.x ) / 25;
			_moveY = ( _endPoint.y - this.y ) / 25;
			
			showOrePlusMovie();
		}
		
		
		private var _numSprite:Sprite;
		private var _oreChangeMovie:MovieClip;
		private function showOrePlusMovie():void {
			
			_numSprite = new Sprite();
			(UIMain.getInstance(UIMain.NAME) as UIMain).addChild(_numSprite);
			_numSprite.x = _endPoint.x;
			_numSprite.y = _endPoint.y;
			var _mClass:Class = ApplicationDomain.currentDomain.getDefinition("OrePaperSum") as Class;
			var _plusSp:Sprite = new _mClass() as Sprite;
			_numSprite.addChild(_plusSp);
			(_plusSp["txtSum"] as TextField).text = "+" + String(_plusPaperSum);
			_mClass = null;
			_plusSp = null;
			_numSprite.alpha = 0;
			
			_mClass = ApplicationDomain.currentDomain.getDefinition("OreChangeMovie") as Class;
			_oreChangeMovie = new _mClass() as MovieClip;
			_oreChangeMovie.addFrameScript(_oreChangeMovie.totalFrames - 1, function():void { _oreChangeMovie.stop(); } );
			(UIMain.getInstance(UIMain.NAME) as UIMain).addChild(_oreChangeMovie);
			_oreChangeMovie.x = _endPoint.x;
			_oreChangeMovie.y = _endPoint.y;
			
			UICommand.setPaperNum(_plusPaperSum);
			
			_shadeMovieTimer = new Timer(25, 75);
			_shadeMovieTimer.addEventListener(TimerEvent.TIMER, changeOrePlusMovie);
			_shadeMovieTimer.start();
		}
		
		private function changeOrePlusMovie(event:TimerEvent):void {
			
			if (_shadeMovieTimer.currentCount <= 25) {
				_numSprite.y -= 2;
				_numSprite.alpha += 0.04;
				_numSprite.x -= 0.1;
				_numSprite.scaleX += 0.01;
				_numSprite.scaleY += 0.01;
				if (glodBtn) {
					
					glodBtn.x += _moveX;
					glodBtn.y += _moveY;
					glodBtn.alpha -= 0.04;
				}
			}
			else if (_shadeMovieTimer.currentCount > 50 && _shadeMovieTimer.currentCount < 75) {
				_numSprite.y -= 1;
				_numSprite.alpha -= 0.03;
				_numSprite.x -= 0.1;
				_numSprite.scaleX += 0.01;
				_numSprite.scaleY += 0.01;
			}
			else if (_shadeMovieTimer.currentCount == 75) {
				_shadeMovieTimer.reset();
				_shadeMovieTimer.removeEventListener(TimerEvent.TIMER, changeOrePlusMovie);
				_shadeMovieTimer = null;
				
				(UIMain.getInstance(UIMain.NAME) as UIMain).removeChild(_oreChangeMovie);
				(UIMain.getInstance(UIMain.NAME) as UIMain).removeChild(_numSprite);
				_oreChangeMovie = null;
				_numSprite = null;
				(UIMain.getInstance(OptionMainLayer.NAME) as OptionMainLayer).removeOrePaper(this);
				
			}
		}
	}//end OrePaper

}