///////////////////////////////////////////////////////////
//  CloudLayer.as
//  Macromedia ActionScript Implementation of the Class CloudLayer
//  Generated by Enterprise Architect
//  Created on:      05-三月-2012 18:28:12
//  Original author: LuXianli
///////////////////////////////////////////////////////////

package com.raytoon.cannonfodder.puremvc.view.ui.toolsLayer.element
{
	import com.raytoon.cannonfodder.tools.utils.GlobalVariable;
	import com.raytoon.cannonfodder.tools.utils.UICommand;
	import flash.display.DisplayObject;
	import flash.display.Sprite;
	import flash.events.Event;
	import flash.events.MouseEvent;
	/**
	 * @author LuXianli
	 * @version 1.0
	 * @created 05-三月-2012 18:28:12
	 */
	public class CloudLayer extends Sprite
	{
		public function CloudLayer(){
			showCloud();
		}
		
		private var _cloudArr:Array = [];
		private var _cloudSum:int = 0;
		/**
		 * 显示云 运动
		 */
		public function showCloud():void {
			
			_cloudSum = 3 + Math.random() * 3;
			for (var i:int = 0; i < _cloudSum; i ++ ) {
				
				var _cloudNum:int = Math.random() * 3 + 1;
				var _mClass:Class = UICommand.getClass("Cloud" + _cloudNum.toString());
				var obj:Object = new _mClass();
				_mClass = null;
				addChild(obj as DisplayObject);
				obj.cloud.gotoAndStop(1);
				obj.cloudDown.gotoAndStop(1);
				obj["cloud"].addEventListener(MouseEvent.CLICK, cloudClickHandler);
				obj.flag = false;
				_cloudArr.push(obj);
				obj.x = Math.random() * GlobalVariable.STAGE_WIDTH;
				obj.y = Math.random() * (GlobalVariable.STAGE_HEIGHT - obj.height);
				obj = null;
			}
			sortCloud();
			if (!hasEventListener(Event.ENTER_FRAME)) addEventListener(Event.ENTER_FRAME, enterFrameHandler);
		}
		
		/**
		 * 云横向运动
		 * @param	event
		 */
		private function enterFrameHandler(event:Event):void {
			
			for each (var obj:Object in _cloudArr) {
				
				obj.x > GlobalVariable.STAGE_WIDTH?obj.x = -obj.width:obj.x += Math.random();
			}
		}
		
		private var _cloudClearArr:Array = [];
		/**
		 * 云点击处理
		 * @param	event
		 */
		private function cloudClickHandler(event:MouseEvent):void {
			
			var obj:Object = event.currentTarget.parent;
			obj["cloud"].removeEventListener(MouseEvent.CLICK, cloudClickHandler);
			var _index:int = _cloudArr.indexOf(obj);
			if (_index != -1)_cloudArr.splice(_index, 1);
			obj.addEventListener("cloudClear", cloudClearHandler);
			obj.cloud.play();
			obj.cloudDown.play();
			_cloudClearArr.push(obj);
		}
		/**
		 * 清除动画播放完成
		 * @param	event
		 */
		private function cloudClearHandler(event:Event):void {
			
			for (var i:int = 0; i < _cloudClearArr.length; i ++ ) {
				
				if (_cloudClearArr[i].flag == true) {
					
					removeChild(_cloudClearArr[i] as DisplayObject);
					_cloudClearArr[i].removeEventListener("cloudClear", cloudClearHandler);
					_cloudClearArr.splice(i, 1);
					
					var _cloudNum:int = Math.random() * 3 + 1;
					var _mClass:Class = UICommand.getClass("Cloud" + _cloudNum.toString());
					var obj:Object = new _mClass();
					_mClass = null;
					addChild(obj as DisplayObject);
					obj.cloud.gotoAndStop(1);
					obj.cloudDown.gotoAndStop(1);
					obj["cloud"].addEventListener(MouseEvent.CLICK, cloudClickHandler);
					obj.flag = false;
					_cloudArr.push(obj);
					obj.x = -Math.random() * GlobalVariable.STAGE_WIDTH;
					obj.y = Math.random() * (GlobalVariable.STAGE_HEIGHT - obj.height);
					obj = null;
				}
			}
			sortCloud();
		}
		
		private function sortCloud():void {
			
			for each (var obj:Object in _cloudArr) {
				
				removeChild(obj as DisplayObject);
			}
			
			for (var i:int = 0; i < _cloudArr.length; i ++ ) {
				
				for (var j:int = i; j < _cloudArr.length; j ++ ) {
					
					var objA:Object = _cloudArr[i];
					if (_cloudArr[i].y > _cloudArr[j].y) {
						
						_cloudArr[i] = _cloudArr[j];
						_cloudArr[j] = objA;
					}
					objA = null;
				}
			}
			
			for each (var objB:Object in _cloudArr) {
				
				addChild(objB as DisplayObject);
			}
		}
		
		/**
		 * 清楚云，及事件
		 */
		public function clear():void {
			
			if (hasEventListener(Event.ENTER_FRAME)) removeEventListener(Event.ENTER_FRAME, enterFrameHandler);
			
			for each (var obj:Object in _cloudArr) {
				
				removeChild(obj as DisplayObject);
				obj["cloud"].removeEventListener(MouseEvent.CLICK, cloudClickHandler);
				
			}
			_cloudArr = [];
		}
	}//end CloudLayer

}