// /////////////////////////////////////////////////////////
// EventNameList.as
// Macromedia ActionScript Implementation of the Class EventNameList
// Generated by Enterprise Architect
// Created on:      01-六月-2011 10:59:00
// Original author: LuXianli
// /////////////////////////////////////////////////////////
package com.raytoon.cannonfodder.tools.utils
{
	/**
	 * ui发送事件时，事件名
	 * @author LuXianli
	 * @version 1.0
	 * @created 01-六月-2011 10:59:00
	 */
	public class EventNameList
	{
		public static const LIB_LOAD_COMPLETE:String = "libLoadComplete";
		// 主素材库加载完成事件
		public static const MAIN_LIBRARY_LOAD_COMPLETE:String = "mainLibraryLoadComplete";
		// libraryList 地址列表 素材 已加载完成 事件
		public static const SHOW_CHAPTER:String = "showChapter";
		// 显示攻击章节地图
		public static const DYNAMIC_LOAD_COMPLETE:String = "dynamicLoadComplete";
		// 素材动态加载完成
		//public static const DEFENCE_TOWER_INFO:String = "defenceTowerInfo";
		// 布防时传递布防塔信息 dataObj:{"towerType":"defenceTower","id":101}
		public static const BACKGROUND_MAP_INFO:String = "backgroundMapInfo";
		
		public static const UI_GET_DATA:String = "UIGetData";
		public static const UI_SAVE_DATA:String = "UISaveData";
		
		public static const INTRO_MOVIE_PLAY_COMPLETE:String = "introMoviePlayComplete";
		//开场动画播放完毕
		public static const INTRO_MOVIE_LOAD_COMPLETE:String = "introMovieLoadCompelte";
		//开场动画加载完毕
		public static const NEW_USER_MOVIE_LOAD_COMPLETE:String = "newUserMovieLoadComplete";
		//新手动画加载完毕
		public function EventNameList()
		{
		}
	}
	// end EventNameList
}