///////////////////////////////////////////////////////////
//  MouseManager.as
//  Macromedia ActionScript Implementation of the Class MouseManager
//  Generated by Enterprise Architect
//  Created on:      5-一月-2012 16:25:44
//  Original author: LuXianli
///////////////////////////////////////////////////////////

package com.raytoon.cannonfodder.tools.utils 
{
	
	import flash.display.Bitmap;
	import flash.display.BitmapData;
	import flash.display.Loader;
	import flash.display.Sprite;
	import flash.events.Event;
	import flash.events.IOErrorEvent;
	import flash.geom.Point;
	import flash.net.URLRequest;
	import flash.ui.Mouse;
	import flash.ui.MouseCursorData;

	/**
	 * @author LuXianli
	 * @version 1.0
	 * @created 5-一月-2012 16:25:44
	 */
	public class MouseManager extends Sprite
	{
		
		/** 自动 */  
		public static const AUTO : String = "auto";  
		/** 指针 */  
		public static const ARROW : String = "arrow";  
		public static const BUTTON : String = "button";  
		public static const HAND : String = "hand";  
		public static const IBEAM : String = "ibeam";  
		/** 对话 */  
		public static const DIALO : String = "dialo";  
		/** 警告 */  
		public static const WARNING : String = "warning";  
		/** 正确 */  
		public static const CORRECT : String = "correct";  
		  
		// ---------------------------------- 我是优美的长分隔线 ---------------------------------- //  
		/** 地图鼠标点击特效 */  
		public static var MapMouseDownEffect:Class;  
		// ---------------------------------- 我是优美的长分隔线 ---------------------------------- //  
		private static var _loader : Loader;  
		/** 鼠标ICO资源文件路径 */  
		public static var url:String = "swf/MouseIco.swf";  
  
		public static function load() : void  
		{  
			_loader = new Loader();  
			var request : URLRequest = new URLRequest(url);  
			_loader.contentLoaderInfo.addEventListener(Event.COMPLETE, loader_complete);  
			_loader.contentLoaderInfo.addEventListener(IOErrorEvent.IO_ERROR, loader_ioErrorHandler);  
			_loader.load(request);  
		}  
  
		private static function loader_ioErrorHandler(event : IOErrorEvent) : void  
		{  
			trace("MouseManager中加载鼠标图标出错------ioErrorHandler: " + event);  
		}  
  
		private static function loader_complete(event : Event) : void  
		{  
			var vector:Vector.<BitmapData>;  
			var mouseCursorData :MouseCursorData;  
			var ICO:Class;
			//指针,自动  
			vector = new Vector.<BitmapData>();  
			mouseCursorData = new MouseCursorData();  
			ICO = _loader.contentLoaderInfo.applicationDomain.getDefinition("DefaultStyle") as Class;  
			vector.push(new ICO());  
			mouseCursorData.data = vector;
			mouseCursorData.hotSpot = new Point(0,0);
			Mouse.registerCursor(ARROW, mouseCursorData);  
			//对话  
			//vector = new Vector.<BitmapData>();  
			//mouseCursorData = new MouseCursorData();  
			//for(var i:int =0; i< 10; i++)  
			//{  
				//ICO = _loader.contentLoaderInfo.applicationDomain.getDefinition("dialog" + i) as Class;  
				//vector.push(new ICO());  
			//}  
			//mouseCursorData.data = vector;  
			//Mouse.registerCursor(DIALO, mouseCursorData);  
			//警告  
			//vector = new Vector.<BitmapData>();  
			//mouseCursorData = new MouseCursorData();  
			//ICO = _loader.contentLoaderInfo.applicationDomain.getDefinition("Warning") as Class;  
			//vector.push(new ICO());  
			//mouseCursorData.data = vector;  
			//Mouse.registerCursor(WARNING, mouseCursorData);  
			//正确  
			//vector = new Vector.<BitmapData>();  
			//mouseCursorData = new MouseCursorData();  
			//ICO = _loader.contentLoaderInfo.applicationDomain.getDefinition("Correct") as Class;  
			//vector.push(new ICO());  
			//mouseCursorData.data = vector;  
			//Mouse.registerCursor(CORRECT, mouseCursorData);  
		}  
		  
		public static function set cursor(str:String):void  
		{  
			Mouse.cursor = str;  
		}  
		  
		public static function get cursor():String  
		{  
			return Mouse.cursor;  
		}  
		
	}

}