// // // // ///////////////////////////////////////////////////
// ProxyNotificationNameList.as
// Macromedia ActionScript Implementation of the Class ProxyNotificationNameList
// Generated by Enterprise Architect
// Created on:      01-六月-2011 16:19:36
// Original author: LuXianli
// // // // ///////////////////////////////////////////////////
package com.raytoon.cannonfodder.tools.utils
{
	/**
	 * model 层发出通知，通知名
	 * @author LuXianli
	 * @version 1.0
	 * @created 01-六月-2011 16:19:36
	 */
	public class ProxyNotificationNameList
	{
		// 获得用户信息
		public static const GET_USER:String = "getUser";
		public static const MAIN_XML_RECEIVED:String = "mainXmlReveived";
		// 主配置文件 得到
		public static const OTHER_XML_RECEIVED:String = "otherXmlReceived";
		public static const UI_GET_DATA:String = "UIGetData";
		public static const UI_SAVE_DATA:String = "UISaveData";
		public static const IS_NEW_USER:String = "isNewUser";
		//是否是新手

		// 其他配置文件加载完成
		public function ProxyNotificationNameList()
		{
		}
	}
	// end ProxyNotificationNameList
}