// // // // // // // // // // // // // // // // // // // // // // // // // // // // //                             /
// ConstPath.as
// Macromedia ActionScript Implementation of the Class ConstPath
// Generated by Enterprise Architect
// Created on:      02-六月-2011 12:16:44
// Original author: LuXianli
// // // // // // // // // // // // // // // // // // // // // // // // // // // // //                             /
package com.raytoon.cannonfodder.tools.net {
	/**
	 * @author LuXianli
	 * @version 1.0
	 * @created 02-六月-2011 12:16:45
	 */
	public class ConstPath {
		// 官网
//		 public static var SESSION : String = "jxs";
//		 public static var DATA_SERVER_URL : String = "58.83.236.251";
//		 public static var DATA_SERVER_PORT : int = 7001;
		// 开心正式
		// public static var SESSION : String = "109747183_100027036_109747183_1339656482_4d3fa4f475a400953c3be604c9a2ee5b";
		// public static var DATA_SERVER_URL : String = "58.83.217.16";
		// public static var DATA_SERVER_PORT : int = 7011;
		// 开心测试
		// public static var SESSION : String = "104750636_100006612_104750636_1339478006_3416b30f939f6ea45907ce1f7f411abd";
		// public static var DATA_SERVER_URL : String = "58.83.236.251";
		// public static var DATA_SERVER_PORT : int = 7011;
		// 人人测试
		public static var SESSION : String = "2.19b962f47c7c243af3f9b93927243363.3600.1341986400-346128546";
		public static var DATA_SERVER_URL : String = "58.83.236.251";
		public static var DATA_SERVER_PORT : int = 7021;
		// 人人正式
		// public static var SESSION : String = "2.3709b4bba25ecbd5478004379b870e08.3600.1340614800-269968850";
		// public static var DATA_SERVER_URL : String = "58.83.236.250";
		// public static var DATA_SERVER_PORT : int = 7021;
		//		//		//
		// 资源地址前缀
		public static var MATERIAL_PATH : String = "";
		//
		public static const SWF_PATH : String = "swf/";
		// 矢量素材  服务器相对地址
		public static const PNG_PATH : String = "png/";
		// 地图素材   服务器地址
		public static const MAP_PATH : String = "map/";
		// 位图素材  服务器相对地址
		public static const SWF_SUFFIX : String = ".swf";
		// 矢量素材后缀名
		public static const BITMAP_PATH : String = "";

		public function ConstPath() {
		}
	}
	// end ConstPath
}