///////////////////////////////////////////////////////////
//  NewUserTraining .as
//  Macromedia ActionScript Implementation of the Class NewUserTraining 
//  Generated by Enterprise Architect
//  Created on:      29-十二月-2011 11:09:58
//  Original author: LuXianli
///////////////////////////////////////////////////////////

package com.raytoon.cannonfodder.puremvc.view.ui.newUserLayer
{
	import com.raytoon.cannonfodder.puremvc.view.ui.UIMain;
	import com.raytoon.cannonfodder.tools.utils.UIClass;
	import com.raytoon.cannonfodder.tools.utils.UICommand;
	import com.raytoon.cannonfodder.tools.utils.UITransition;
	import com.raytoon.cannonfodder.tools.xml.XMLSource;
	
	import flash.display.DisplayObject;
	import flash.display.Sprite;
	import flash.events.MouseEvent;
	/**
	 * @author LuXianli
	 * @version 1.0
	 * @created 29-十二月-2011 11:09:58
	 */
	public dynamic class NewUserTrainingCamp extends Sprite
	{
		public static const NAME:String = "NewUserTrainingCamp";
		public function NewUserTrainingCamp () {
			
			var _mClass:Class = UICommand.getClass(UIClass.ANNOUNCEMENT);
			_traingCamp = new _mClass();
			addChild(_traingCamp as DisplayObject);
			_mClass = null;
			_traingCamp["close"].addEventListener(MouseEvent.CLICK,closeThis);
			_traingCamp["animation"].addEventListener(MouseEvent.CLICK, (UIMain.getInstance(UIMain.NAME) as UIMain).showIntroMovie);
			_traingCamp["help"].comp.enabled = false;
			_beginnerXmlList  = XMLSource.getXMLSource("UISite.xml").beginner;
			_traingCamp["title1"].text = String(_beginnerXmlList.title1);
			_traingCamp["title2"].text = String(_beginnerXmlList.title2);
		}
		
		private var _traingCamp:Object;
		private var _beginnerXmlList:XMLList;
		public function showTraingCamp(obj:Object):void {
			
			var _arr:Array = obj as Array;
			
			for (var i:int = 0; i < 4; i ++ ) {
				
				//var obj:Object = _traingCamp["box"].getChildAt(i);
				obj.dataNpcID = _arr[i][0];
				obj.dataLevel = _arr[i][1];
				obj.dataMapID = _arr[i][2];
				obj["title1"].text = String(_beginnerXmlList.map.name[i]);
				obj["title2"].text = String(_beginnerXmlList.user.name[i]);
				obj["submit"].addEventListener(MouseEvent.CLICK,startTraining);
			}
			
		}
		
		private function closeThis(event:MouseEvent):void {
			
			//UITransition.beginnerToStart();
		}
		
		private function startTraining(event:MouseEvent):void {
			
			var obj:Object = event.currentTarget.parent;
			//UITransition.beginnerToSelectAttackRole(obj.dataNpcID, obj.title2.text, obj.dataLevel, obj.dataMapID);
		}
	}//end NewUserTraining 

}