///////////////////////////////////////////////////////////
//  ArticleBlood.as
//  Macromedia ActionScript Implementation of the Class ArticleBlood
//  Generated by Enterprise Architect
//  Created on:      11-十月-2011 17:41:54
//  Original author: LuXianli
///////////////////////////////////////////////////////////

package com.raytoon.cannonfodder.tools
{
	import flash.display.DisplayObject;
	import flash.display.MovieClip;
	import flash.display.Sprite;
	import flash.system.ApplicationDomain;
	/**
	 * @author LuXianli
	 * @version 1.0
	 * @created 11-十月-2011 17:41:54
	 */
	public class ArticleBlood extends Sprite
	{
		private var _elementArticle:Object;
		public function ArticleBlood(){
			
			var _mClass:Class = ApplicationDomain.currentDomain.getDefinition("ElementArticle") as Class;
			_elementArticle = new _mClass();
			addChild(_elementArticle as DisplayObject);
			_elementArticle.x = -_elementArticle.width/2;
		}
		private var _armorNum:Number = 0;
		private var _HPNum:Number = 0;
		/**
		 * 更改血条长度
		 * @param	nowHP
		 * @param	allHP
		 * @param	nowArmor
		 * @param	allArmor
		 */
		public function showArticle(nowHP:int,allHP:int,nowArmor:int,allArmor:int,level:int = 1):void {
			
			if (_elementArticle) {
				
				_elementArticle["levelTxt"].text = level.toString();
				
				if ((Number(nowArmor / allArmor) <= 0) || allArmor <= 0) {
					_elementArticle["armor"].visible = false;
					_elementArticle["blood"].y =  _elementArticle["blood"].height / 2;
				}else {
					_elementArticle["armor"].visible = true;
					_elementArticle["armor"]["article"].scaleX = Number(nowArmor / allArmor);
					
					_elementArticle["blood"].y = _elementArticle["armor"].height;
				}
				
				if ((Number(nowHP / allHP) <= 0) || allHP <=0) {
					_elementArticle["blood"].visible = false;
					
				}else {
					_elementArticle["blood"].visible = true;
					_elementArticle["blood"]["article"].scaleX = Number(nowHP / allHP);
				}
			}
		}
	}//end ArticleBlood

}