///////////////////////////////////////////////////////////
//  Node.as
//  Macromedia ActionScript Implementation of the Class UIMain
//  Generated by Enterprise Architect
//  Created on:      13-六月-2011 10:40:10
//  Original author: LuXianli
///////////////////////////////////////////////////////////
package com.raytoon.cannonfodder.tools.aStar
{
	import com.raytoon.cannonfodder.tools.utils.GlobalVariable;
	import flash.geom.Rectangle;
	/**
	 * Represents a specific node evaluated as part of a pathfinding algorithm.
	 * 寻径矩阵 节点
	 * @author LuXianli
	 * @version 1.0
	 * @updated 13-六月-2011 10:43:25
	 */
	public class Node
	{
		public var x:int;//矩阵横向索引
		public var y:int;//矩阵纵向索引
		public var unitX:int;//节点中心X坐标
		public var unitY:int;//节点中心Y坐标
		public var f:Number;
		public var g:Number;
		public var h:Number;
		public var walkable:Boolean = true; //是否可行走
		public var parent:Node;//父节点（上一个可行走节点）
		public var child:Node;//子节点（下一个可行走节点）
		public var costMultiplier:Number = 1.0;
		public var isAppear:Boolean = true;// 是否可以出现不妨碍行走物品
		public var rectangle:Rectangle;//节点覆盖范围
		public var attackAttack:int = 0;//当前攻击方在此节点内的总攻击力
		public var defenceAttack:int = 0;//当前防守方在此节点内的总攻击力
		public var attackArr:Array = [];//当前在此节点内的攻击单元总数
		public var defenceArr:Array = [];//当前在此节点内防守单元总数
		public function Node(x:int, y:int,unitX:int,unitY:int)
		{
			this.x = x;
			this.y = y;
			this.unitX = unitX;
			this.unitY = unitY;
			rectangle = new Rectangle(unitX - GlobalVariable.RECT_WIDTH / 2, unitY - GlobalVariable.RECT_HEIGHT / 2, GlobalVariable.RECT_WIDTH, GlobalVariable.RECT_HEIGHT);
		}
	}
}