///////////////////////////////////////////////////////////
//  InformationLayer.as
//  Macromedia ActionScript Implementation of the Class InformationLayer
//  Generated by Enterprise Architect
//  Created on:      01-六月-2011 14:20:20
//  Original author: LuXianli
///////////////////////////////////////////////////////////

package com.raytoon.cannonfodder.puremvc.view.ui.informationLayer
{
	import com.raytoon.cannonfodder.puremvc.view.ui.UIMain;
	import com.raytoon.cannonfodder.tools.utils.GlobalVariable;
	import com.raytoon.cannonfodder.tools.utils.MouseStyleNow;
	import flash.display.DisplayObject;
	import flash.display.Shape;
	import flash.display.Sprite;
	import flash.events.Event;
	import flash.events.MouseEvent;
	import flash.system.ApplicationDomain;
	import flash.text.TextField;
	import flash.ui.Mouse;
	/**
	 * @author LuXianli
	 * @version 1.0
	 * @created 01-六月-2011 14:20:20
	 */
	public class InformationLayer extends Sprite
	{
		public static const NAME:String = "InformationLayer";
		public function InformationLayer(){
			UIMain.setInstance(InformationLayer.NAME,this);
		}
		
		public function whiteStage():void {
			
			if (!hasEventListener(Event.ENTER_FRAME)) {
				
				addEventListener(Event.ENTER_FRAME, whiteStageHandler);
			}
			else {
				_stageShape.alpha = 1;
				_frameSum = 1;
			}
		}
		
		private var _frameSum:int = 0;
		private var _stageShape:Shape;
		private function whiteStageHandler(event:Event):void {
			
			_frameSum ++;
			if (_frameSum == 1) {
				
				_stageShape = new Shape();
				_stageShape.graphics.beginFill(0xFFFFFF);
				_stageShape.graphics.drawRect(0, 0, GlobalVariable.STAGE_WIDTH, GlobalVariable.STAGE_HEIGHT);
				_stageShape.graphics.endFill();
				addChild(_stageShape);
			}
			else if(_frameSum > 1 && _frameSum < 15){
				_stageShape.alpha -= 0.05;
			}
			else if (_frameSum == 15) {
				
				removeEventListener(Event.ENTER_FRAME, whiteStageHandler);
				removeChild(_stageShape);
				_stageShape.graphics.clear();
				_stageShape = null;
				_frameSum = 0;
			}
			
		}
		
		private var _dSp:Sprite;
		public function showDefenceInfo(str:String):void {
			
			_dSp = new Sprite();
			_dSp.graphics.beginFill(0xFFFFFF);
			_dSp.graphics.drawRect(0, 0, GlobalVariable.STAGE_WIDTH, GlobalVariable.STAGE_HEIGHT);
			_dSp.graphics.endFill();
			addChild(_dSp);
			var _mClass:Class = ApplicationDomain.currentDomain.getDefinition("com.paohui.ui.popup.set.SetContent") as Class;
			var _btn:Object = new _mClass();
			_mClass = null;
			_dSp.addChild(_btn["submit"] as DisplayObject);
			_btn["submit"].addEventListener(MouseEvent.CLICK, btnClickHandler);
			_btn["submit"].y = 0;
			var _txt:TextField = new TextField();
			_dSp.addChild(_txt);
			_txt.x = 20;
			_txt.y = 50;
			_txt.width = 700;
			_txt.height = 500;
			_txt.wordWrap = true;
			_txt.text = str;
			
		}
		
		private function btnClickHandler(event:MouseEvent):void {
			
			removeChild(_dSp);
			_dSp = null;
			
		}
	}//end InformationLayer

}