///////////////////////////////////////////////////////////
//  BuffLayer.as
//  Macromedia ActionScript Implementation of the Class BuffLayer
//  Generated by Enterprise Architect
//  Created on:      29-九月-2011 15:01:01
//  Original author: LuXianli
///////////////////////////////////////////////////////////

package com.raytoon.cannonfodder.puremvc.view.ui.buffLayer
{
	import com.raytoon.cannonfodder.puremvc.model.vo.CannonFodderVO;
	import com.raytoon.cannonfodder.puremvc.view.ui.UIMain;
	import com.raytoon.cannonfodder.puremvc.view.ui.techTreeLayer.TechTreeLayer;
	import com.raytoon.cannonfodder.puremvc.view.ui.toolsLayer.ToolsLayer;
	import com.raytoon.cannonfodder.tools.utils.GlobalVariable;
	import com.raytoon.cannonfodder.tools.utils.UICommand;
	import com.raytoon.cannonfodder.tools.utils.UICreate;
	import com.raytoon.cannonfodder.tools.utils.UIName;
	import com.raytoon.cannonfodder.tools.utils.UIState;
	import com.raytoon.cannonfodder.tools.utils.UIXML;
	import com.raytoon.cannonfodder.tools.xml.XMLSource;
	
	import flash.display.DisplayObject;
	import flash.display.DisplayObjectContainer;
	import flash.display.MovieClip;
	import flash.display.Sprite;
	import flash.events.MouseEvent;
	import flash.system.ApplicationDomain;
	/**
	 * @author LuXianli
	 * @version 1.0
	 * @created 29-九月-2011 15:01:01
	 */
	public class BuffLayer extends Sprite
	{
		public static const NAME:String = "BuffLayer";
		public function BuffLayer(){
			UIMain.setInstance(NAME, this);
			
		}
		private var _buffArr:Array = new Array();
		private var _buffInfoArr:Array = [];
		private var _bgObj:Object;
		/**
		 * 显示buff，道具
		 * @param	obj
		 */
		public function showBuff(obj:Object = null):void {
			removeBuff();
			
			_buffInfoArr = UICommand.t.userData[5] as Array;//_buffObj.buff as Array;
			var _buffLen:int = _buffInfoArr ? _buffInfoArr.length : 0;
			if (_buffLen == 0) {
				return;
			}
			else{
				
				
				var flag:Boolean = true;
				
				for each (var tObj:Object in _buffInfoArr) {
					
					if (int(XMLSource.getXMLSource("Props.xml").prop.(@id == tObj.id).isShow) == 1) flag = false;
				}
				
				if (flag) return;
			}
			var _buffXml:XML = XMLSource.getXMLSource("Props.xml");
			var _bgClass:Class = ApplicationDomain.currentDomain.getDefinition("com.paohui.ui.userInfo.Buff") as Class;
			_bgObj = new _bgClass() as Object;
			addChild(_bgObj as DisplayObject);
			var i:int = 0;
			for  each(var bObj:Object in _buffInfoArr ) {
				
				var _buffXmlList:XMLList = _buffXml.prop.(@id == bObj.id);
				if (int(_buffXmlList.isShow) == 0) continue;
				var _buffClass:Class = ApplicationDomain.currentDomain.getDefinition(String(_buffXmlList.name)) as Class;
				var _buffMC:MovieClip = new _buffClass() as MovieClip;
				_bgObj["box"].getChildAt(i).addChild(_buffMC);
				
				_buffMC.width = 15;
				_buffMC.height = 15;
				_buffMC.x = 2;
				_buffMC.y = 2;
				_buffMC.dataID = bObj.id;
				_buffMC.dataStartTime = bObj.startTime;
				_buffMC.dataSurplus = bObj.surplus;
				_buffMC.dataTitle = String(_buffXmlList.langName);
				_buffMC.dataInfo = String(_buffXmlList.info);
				_buffMC.addEventListener(MouseEvent.ROLL_OVER, buffOver);
				_buffMC.addEventListener(MouseEvent.ROLL_OUT, UICommand.t.mouseEvent);
				_buffMC.addEventListener(MouseEvent.CLICK, buffClick);
				_buffArr.push(_buffMC);
				_buffXmlList = null;
				_buffClass = null;
				_buffMC = null;
				i ++;
			}
			
			_buffXml = null;
		}
		/**
		 * 移除指定buff
		 * @param	dataID
		 */
		public function removeBuff(dataID:int = 0):void {
			_buffInfoArr = [];
			if (dataID == 0) {
				
				for (var m:int = 0; m < _buffArr.length; m ++) {
					
					while (_bgObj["box"].getChildAt(i).numChildren) {
						_bgObj["box"].getChildAt(i).removeChildAt(0);
					}
					
				}
				_buffArr = [];
			}
			else {
				
				for (var i:int = 0; i < _buffArr.length; i ++ ) {
					
					if (_buffArr[i].dataID == dataID) {
						
						_buffArr[i].visible = false;
						_buffArr.splice(i, 1);
						return;
					}
				}
			}
		}
		
		private function buffOver(event:MouseEvent):void {
			
			var obj:Object = event.currentTarget;
			UICreate.createTooltips(obj.dataTitle, obj.dataInfo, obj as DisplayObject);
			obj = null;
			event = null;
		}
		private function buffOut(event:MouseEvent):void {
			event = null;
		}
		
		private function buffClick(event:MouseEvent):void {
			
			var obj:Object = event.currentTarget;
			UICreate.popupPrompt(String(UIXML.uiXML.bag.info[2]) + UIName.CHAR_RETURN_WRAP, UIState.REMOVE_BUFF, true, obj.dataID);
			obj = null;
			event = null;

		}
		/**
		 * 检查buff 是否过期
		 */
		public function removExpiredBuff():void {
			
			var _buffXml:XML = XMLSource.getXMLSource("Props.xml");
			for (var i:int = 0; i < _buffArr.length; i++ ) {
				
				var _buffXmlList:XMLList = _buffXml.prop.(@id == _buffArr[i].dataID);
				if (_buffArr[i].dataStartTime > 0) {
					var _propTime:int = int(_buffXmlList.buffEnableTime) * 3600 * 1000;
					if (TechTreeLayer.SERVER_NOW_TIME - _buffArr[i].dataStartTime > _propTime) {
						removeChild(_buffArr[i]);
						_buffArr.splice(i, 1);
					}
				}else {
					if (_buffArr[i].surplus <= 0) {
						removeChild(_buffArr[i]);
						_buffArr.splice(i, 1);
					}
				}
				_buffXmlList = null;
			}
		}
		/**
		 * 检查此种buff是否存在
		 * @param	buffType  buff 类型
		 * @return
		 */
		public function checkBuffView(buffType:String):int {
			
			var _buffXml:XML = XMLSource.getXMLSource("Props.xml");
			_buffInfoArr = UICommand.t.userData[5] as Array;
			for each(var obj:Object in _buffInfoArr) {
				
				if (String(_buffXml.prop.(@id == obj.id).buffType) == buffType) 
					return obj.id as int;
			}
			_buffXml = null;
			return 0;
		}
		/**
		 * 获得buff 剩余次数
		 * @param	id
		 * @return
		 */
		public function getSurplus(id:int):int {
			
			for each(var obj:Object in _buffInfoArr) {
				
				if (int(obj.id) == id) 
					return obj.surplus as int;
			}
			return 0;
		}
		
		/**
		 * 次数使用buff  减少buff 剩余次数
		 * @param	buffType
		 */
		public function reduceBuffSum(buffType:String):void {
			
			var _buffXml:XML = XMLSource.getXMLSource("Props.xml");
			for (var i:int = 0; i < _buffArr.length; i++ ) {
				
				var _buffType:String = String(_buffXml.prop.(@id == _buffArr[i].dataID).buffType);
				var _buffSum:int = int(_buffXml.prop.(@id == _buffArr[i].dataID).buffEnableSum);
				if (_buffType == buffType && _buffSum > 0) 
					_buffArr[i].dataSurplus -= 1;
			}
			_buffXml = null;
			removExpiredBuff();
		}
		/**
		 * 添加手纸翻倍buff
		 */
		public function addPaperBuff():void {
			
			
		}
	}//end BuffLayer

}