///////////////////////////////////////////////////////////
//  InformationLayerMediator.as
//  Macromedia ActionScript Implementation of the Class InformationLayerMediator
//  Generated by Enterprise Architect
//  Created on:      01-六月-2011 14:20:58
//  Original author: LuXianli
///////////////////////////////////////////////////////////

package com.raytoon.cannonfodder.puremvc.view.mediator.informationLayerMediator
{
	import com.raytoon.cannonfodder.puremvc.view.ui.informationLayer.InformationLayer;
	import org.puremvc.as3.interfaces.IMediator;
	import org.puremvc.as3.interfaces.INotification;
	import org.puremvc.as3.patterns.mediator.Mediator;
	/**
	 * @author LuXianli
	 * @version 1.0
	 * @created 01-六月-2011 14:20:58
	 */
	public class InformationLayerMediator extends Mediator implements IMediator
	{
		public static const NAME:String = "InformationLayerMediator";
		public function InformationLayerMediator(viewComponent:InformationLayer){
			super(NAME, viewComponent);
		}
		
		public function get informationLayer():InformationLayer {
			return viewComponent as InformationLayer;
		}
		
		override public function onRegister():void 
		{
			
		}
		
		override public function listNotificationInterests():Array 
		{
			return [];
		}
		
		override public function handleNotification(notification:INotification):void 
		{
			switch (notification.getName()) {
				
			}
		}
		
	}//end InformationLayerMediator

}