///////////////////////////////////////////////////////////
//  XMLSource.as
//  Macromedia ActionScript Implementation of the Class XMLSource
//  Generated by Enterprise Architect
//  Created on:      08-六月-2011 13:47:39
//  Original author: LuXianli
///////////////////////////////////////////////////////////

package com.raytoon.cannonfodder.tools.xml
{
	/**
	 * @author LuXianli
	 * @version 1.0
	 * @created 08-六月-2011 13:47:39
	 */
	public class XMLSource
	{
		private static var XML_ARRAY_DATA:Array = new Array();
		/**
		 * 静态方法，存储加载完成的xml数据
		 * @param	xmlName  xml数据文件名
		 * @param	xmlSource  xml数据文件
		 */
		public static function setXMLSource(xmlName:String, xmlSource:XML):void {
			
			if (xmlName && xmlSource)
				XML_ARRAY_DATA[xmlName] = xmlSource;
		}
		/**
		 * 静态方法，取得指定xml数据
		 * @param	xmlName   xml数据文件名
		 * @return         xml数据
		 */
		public static function getXMLSource(xmlName:String):XML {
			
			if (XML_ARRAY_DATA[xmlName])
				return XML_ARRAY_DATA[xmlName] as XML;
			return null;
		}
		
		public function XMLSource(){

		}

	}//end XMLSource

}